### ISSUE TITLE
Cannot get docker container running

### ISSUE THREAD

**Issue by guicapanema** [fixerAPI/fixer#94]
Hello there!

I'm trying to get a local Fixer container up and running, but I'm having problems when running the "seed data" command:

`docker-compose run web rake db:migrate rates:reload`

<img width="725" alt="captura de tela 2018-01-03 as 11 01 17" src="https://user-images.githubusercontent.com/8330306/34521575-86f3fd60-f075-11e7-9a3c-45edf8fbb982.png">

When first running the `docker-compose up -d` command, rubocop was shown as successfully installed. Any insights on how to get around this?

Thanks!

--- UPDATE

It seems the fixer sets up 3 containers, but one of them (fixer_web) is always exiting with the following error:

```
wait-for-it.sh: waiting 15 seconds for db:5432
wait-for-it.sh: db:5432 is available after 0 seconds
I, [2018-01-03T13:19:29.043911 #1]  INFO -- : Refreshing Gem list
/usr/local/bundle/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:145:in `async_exec': PG::UndefinedTable: ERROR:  relation "currencies" does not exist (Sequel::DatabaseError)
LINE 1: SELECT * FROM "currencies" LIMIT 1
                      ^
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:133:in `block in execute'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:109:in `check_disconnect_errors'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:133:in `execute'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:449:in `_execute'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:273:in `block (2 levels) in execute'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:471:in `check_database_errors'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:273:in `block in execute'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/database/connecting.rb:264:in `block in synchronize'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/connection_pool/single.rb:31:in `hold'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/database/connecting.rb:264:in `synchronize'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:273:in `execute'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/dataset/actions.rb:1085:in `execute'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:563:in `fetch_rows'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/dataset/actions.rb:151:in `each'
	from /usr/local/bundle/gems/sequel_pg-1.8.1/lib/sequel_pg/sequel_pg.rb:81:in `each'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/dataset/actions.rb:85:in `columns!'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/dataset/actions.rb:75:in `columns'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/model/base.rb:242:in `columns'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/model/base.rb:802:in `block (2 levels) in get_db_schema'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/model/base.rb:718:in `block in check_non_connection_error'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/database/transactions.rb:151:in `block in transaction'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/database/connecting.rb:264:in `block in synchronize'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/connection_pool/single.rb:31:in `hold'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/database/connecting.rb:264:in `synchronize'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/database/transactions.rb:145:in `transaction'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/model/base.rb:718:in `check_non_connection_error'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/model/base.rb:802:in `block in get_db_schema'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/model/base.rb:835:in `get_db_schema'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/model/base.rb:637:in `set_dataset'
	from /usr/local/bundle/gems/sequel-5.3.0/lib/sequel/model/base.rb:492:in `inherited'
	from /app/lib/currency.rb:3:in `<top (required)>'
	from /app/lib/bank.rb:3:in `require'
	from /app/lib/bank.rb:3:in `<top (required)>'
	from /app/lib/schedule.rb:3:in `require'
	from /app/lib/schedule.rb:3:in `<top (required)>'
	from config/unicorn.rb:15:in `require'
	from config/unicorn.rb:15:in `block in reload'
	from config/unicorn.rb:13:in `fork'
	from config/unicorn.rb:13:in `reload'
	from /usr/local/bundle/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:84:in `instance_eval'
	from /usr/local/bundle/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:84:in `reload'
	from /usr/local/bundle/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:77:in `initialize'
	from /usr/local/bundle/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:77:in `new'
	from /usr/local/bundle/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:77:in `initialize'
	from /usr/local/bundle/gems/unicorn-5.4.0/bin/unicorn:126:in `new'
	from /usr/local/bundle/gems/unicorn-5.4.0/bin/unicorn:126:in `<top (required)>'
	from /usr/local/bundle/bin/unicorn:29:in `load'
	from /usr/local/bundle/bin/unicorn:29:in `<main>'
```

**Comment by hakanensari** [comment]
Oops, this is a recent change. I obviously must have not tried out the image locally before pushing. I'll fix this, thanks for reporting!
